version: '3.9'

services:

  postgres:
    image: postgres:12
    container_name: psql
    ports: 
      - "0.0.0.0:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/media/postgresql/backup
    environment:
      - POSTGRES_PASSWORD=netology
    restart: always 
